### PR TITLE
add python tab for constructor example

### LINKED ISSUE #117: Interface Specification: Ensure python snippets are available for interfaces with major diff between languages
**Is your request related to a problem? Please describe.**
Only some of the constructors/methods/etc have their python defintions

**Describe the solution you'd like**
Ensure that we have a python definition for every interface/constructor/method etc

### PR DESCRIPTION
**Pull request by andre-merzky**
closes #117

The PR also convert tabs to spaces.

### CODE REVIEW

**Review by SteVwonder — APPROVED** [review]
LGTM!

**Review by hategan — COMMENTED** [review]
I think we should do a global tab to spaces conversion rather than piece-wise. I hope that, no matter which side of the tabs vs spaces we are, we can all agree that mixing them is the worst.

**Comment by andre-merzky** [comment]
> I think we should do a global tab to spaces conversion rather than piece-wise. I hope that, no matter which side of the tabs vs spaces we are, we can all agree that mixing them is the worst.

Agree.  They were mixed, and that didn't work well with the part I was working on - thus did the global replacement, there should be no tabs left.

**Comment by andre-merzky** [comment]
@hategan : can we progress with this one, or do you have concerns?

**Review by hategan — APPROVED** [review]
Sorry.

**Comment by andre-merzky** [comment]
no problem, and thanks!

**Pull request merged**
