### PR TITLE
moved sync vs. async in an appendix

### PR DESCRIPTION
**Pull request by hategan**

### CODE REVIEW

**Review by andre-merzky — APPROVED** [review]
I would suggest to move the appendixes into separate files maybe?  Otherwise that looks good to me.

**Comment by hategan** [comment]
> I would suggest to move the appendixes into separate files maybe? Otherwise that looks good to me.

The linking wouldn't be portable between GH and GH Pages. In GH, the link would have to be to the .md file, whereas in Pages you would either use no extension or .html.

However, I think this problem can be addressed with a bit of JavaScript.

Anyway, you need to decide whether you want this to be done now or we can merge the PR and move this into an issue.

**Comment by andre-merzky** [comment]
> Anyway, you need to decide whether you want this to be done now or we can merge the PR and move this into an issue.

It was a suggestion -- as that, happy to leave this to your judgement :-)

**Comment by hategan** [comment]
> > Anyway, you need to decide whether you want this to be done now or we can merge the PR and move this into an issue.
> 
> It was a suggestion -- as that, happy to leave this to your judgement :-)

Well, you are the one who needs to close the conversation if you are satisfied with the state of things and, if there is nothing else in the review, merge the PR.

**Comment by andre-merzky** [comment]
> Well, you are the one who needs to close the conversation if you are satisfied with the state of things and, if there is nothing else in the review, merge the PR.

fair...

**Pull request merged**
